<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Register the module related resources.
    |--------------------------------------------------------------------------
    |
    | These resources contain the model defined in module and involved field values.
    |
    */
    'resources' => config('core::resources'),

    /*
    |--------------------------------------------------------------------------
    | Register the module permissions.
    |--------------------------------------------------------------------------
    |
    | These permissions are auto generated by module:make-permissions.
    |
    */
    'permissions' => config('core::permissions'),

    /*
    |--------------------------------------------------------------------------
    | Register the module provided default roles without attached any member.
    |--------------------------------------------------------------------------
    |
    | These are not assign to any member, just register in system.
    |
    */
    'roles' => config('core::roles'),

    /*
    |--------------------------------------------------------------------------
    | Custom module data seeder.
    |--------------------------------------------------------------------------
    |
    | In these seeders you can defined the custom actions that will execute when
    | deploy the module.
    */
    'installer' => [
        \Modules\Core\Database\Seeders\DeployTableSeeder::class,
    ]

];