<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Register the module related resources.
    |--------------------------------------------------------------------------
    |
    | These resources contain the model defined in module and involved field values.
    |
    */
    'resources' => config('auth::resources'),

    /*
    |--------------------------------------------------------------------------
    | Register the module permissions.
    |--------------------------------------------------------------------------
    |
    | These permissions are auto generated by module:make-permissions.
    |
    */
    'permissions' => config('auth::permissions'),

    /*
    |--------------------------------------------------------------------------
    | Custom module data seeder.
    |--------------------------------------------------------------------------
    |
    | In these seeders you can defined the custom actions that will execute when
    | deploy the module.
    */
    'installer' => [
        \Modules\Auth\Database\Seeders\DeployTableSeeder::class,
    ]

];