<?php

return [
    'post@api/core/auth/member/new/password' => [
        'module_id' => 'Core',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'get@api/core/auth/forgot/password/link' => [
        'module_id' => 'Core',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'post@api/core/member' => [
        'module_id' => 'Core',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'put@api/core/member/{member_id}' => [
        'module_id' => 'Core',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'get@api/core/member/{member_id}' => [
        'module_id' => 'Core',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'get@api/core/members' => [
        'module_id' => 'Core',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'delete@api/core/member' => [
        'module_id' => 'Core',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'get@api/core/role' => [
        'module_id' => 'Core',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
];
