<?php

return [
    'post@api/auth/member/password' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'get@api/auth/forgot/password/link' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'post@api/auth/member' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'put@api/auth/member' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'get@api/auth/member' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'get@api/auth/members' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'delete@api/auth/member' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'get@api/auth/role' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'post@api/kong/team' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'put@api/kong/team' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'delete@api/kong/team' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'get@api/kong/team' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'get@api/kong/team/list' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'post@api/kong/team/invite' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'get@api/kong/team/members' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'delete@api/kong/team/member' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'put@api/kong/team/role' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'post@api/kong/scene' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'delete@api/kong/scene' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'get@api/kong/scene/list' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'get@api/kong/scene/setting/scene' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'put@api/kong/scene/setting/scene' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'get@api/kong/fields' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
    'get@api/kong/field' => [ 
        'module_id' => 'Auth',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
    ],
];
