<?php

return [
    'post@api/auth/auth/member/new/password' => [
        'module_id' => 'Auth',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'get@api/auth/auth/forgot/password/link' => [
        'module_id' => 'Auth',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'post@api/auth/member' => [
        'module_id' => 'Auth',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'put@api/auth/member/{member_id}' => [
        'module_id' => 'Auth',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'get@api/auth/member/{member_id}' => [
        'module_id' => 'Auth',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'get@api/auth/members' => [
        'module_id' => 'Auth',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'delete@api/auth/member' => [
        'module_id' => 'Auth',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
    'get@api/auth/role' => [
        'module_id' => 'Auth',
        'forked_from' => '',
        'permission_type' => 'forever',
        'permission_link' => '',
        'permission_level' => 10,
        'permission_relevance' => [],
        'permission_like' => [],
        'permission_order' => '',
    ],
];
